grids:
  03x03:
    grid_file: "grids/03x03/data.parquet"
    grid_name: "03x03"
  01x01:
    grid_file: "grids/01x01/data.parquet"
    grid_name: "01x01"
default_monthly_data_location: "data/monthly/"
logging:
  level: "INFO"
  rention_period: 7